os: linux
dist: trusty
sudo: required
language: python
services: docker

env:
  - XVFB=1
  - XVFB=0

before_install:
  # Start up xvfb
  - '[[ "$XVFB" != "1" ]] || /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid
     --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16'

before_script:
  - '[[ "$XVFB" != "1" ]] || export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start'

script:
  # Test startup scripts and trigger build of dev branch
  - ./numgeom_desktop.py -d -n && docker stop $(docker ps -q)
  - ./numgeom_jupyter.py -d -n && docker stop $(docker ps -q)
