language: python

services: docker

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - 'docker build --tag numgeom/desktop:dev . &&
     docker push numgeom/desktop:dev &&
     touch success'
# Trigger build of dev-matlab branch
  - '[[ ! -f success ]] ||
     (git clone -b dev-matlab https://$GIT_USER:$GIT_TOKEN@github.com/numgeom/docker-desktop.git dev-matlab 2> /dev/null &&
      cd dev-matlab &&
      git commit --allow-empty -m "Trigger compilation." &&
      git push && cd ..)'
# Test scripts
  - '[[ ! -f success ]] ||
    (git clone -b master https://github.com/numgeom/docker-desktop.git master 2> /dev/null &&
     master/numgeom_desktop.py -d -n -t dev && docker stop $(docker ps -q) &&
     master/numgeom_jupyter.py -d -n -t dev && docker stop $(docker ps -q))'
  - docker images
